### PR TITLE
Another issue on the noise generator

### PR DESCRIPTION
**Pull request by reginakim**
Hello all, 

Yes I am back, and started to bug you. Sorry and thanks. 

If any of you remember this, I fixed the stupid error I created in the xml file. This time, it looks like the 'New' command of the 'itkAdditiveGaussianNoiseImageFilter.h' having an issue. 

The code only gives a warning (no error!) as following:

/ipldev/scratch/eunyokim/src/BRAINS20111028/BRAINSStandAlone/BRAINSCut/BRAINSFeatureCreators/NoiseGenerator/itkAdditiveGaussianNoiseImageFilter.h: In instantiation of ‘itk::AdditiveGaussianNoiseImageFilter<itk::Image<float, 3u>, itk::Image<float, 3u> >’:
/ipldev/scratch/eunyokim/src/BRAINS20111028/BRAINSStandAlone/BRAINSCut/BRAINSFeatureCreators/NoiseGenerator/NoiseGenerator.cxx:38:   instantiated from here
/ipldev/scratch/eunyokim/src/BRAINS20111028/build-Darwin-Debug/ITKv4/Modules/Core/Common/include/itkImageSource.hxx:288: warning: ‘void itk::ImageSource<TOutputImage>::ThreadedGenerateData(const typename TOutputImage::RegionType&, itk::ThreadIdType) [with TOutputImage = itk::Image<float, 3u>]’ was hidden
/ipldev/scratch/eunyokim/src/BRAINS20111028/BRAINSStandAlone/BRAINSCut/BRAINSFeatureCreators/NoiseGenerator/itkAdditiveGaussianNoiseImageFilter.hxx:42: warning:   by ‘void itk::AdditiveGaussianNoiseImageFilter<TInputImage, TOutputImage>::ThreadedGenerateData(const typename itk::InPlaceImageFilter<TInputImage, TOutputImage>::OutputImageRegionType&, int) [with TInputImage = itk::Image<float, 3u>, TOutputImage = itk::Image<float, 3u>]’
Linking CXX shared library /ipldev/scratch/eunyokim/src/BRAINS20111028/build-Darwin-Debug/lib/libNoiseGeneratorLib.dylib
ld: warning: directory not found for option '-L/IPLlinux/ipldev/scratch/eunyokim/src/BRAINS20111028/build-Darwin-Debug/OpenCV-install/share/OpenCV/3rdparty/lib'
[ 99%] Built target NoiseGeneratorLib
Linking CXX executable /ipldev/scratch/eunyokim/src/BRAINS20111028/build-Darwin-Debug/lib/NoiseGenerator
ld: warning: directory not found for option '-L/IPLlinux/ipldev/scratch/eunyokim/src/BRAINS20111028/build-Darwin-Debug/OpenCV-install/share/OpenCV/3rdparty/lib'
[100%] Built target NoiseGenerator
[ 78%] No install step for 'BRAINSTools'
[ 78%] Completed 'BRAINSTools'
[100%] Built target BRAINSTools

And then if I try to run the binary, I get the following error::

/ipldev/scratch/eunyokim/src/BRAINS20111028/build-Darwin-Debug/lib/NoiseGenerator --inputVolume /ipldev/scratch/eunyokim/src/BRAINS20111028/build-Darwin-Debug/ReferenceAtlas-build/Atlas/Atlas_20120104/template_t1.nii.gz --outputVolume ~/Desktop/outputTest.nii.gz --inputGaissianMean 0 --inputGaussianStandardDeviation 1
10::/ipldev/scratch/eunyokim/src/BRAINS20111028/BRAINSStandAlone/BRAINSCut/BRAINSFeatureCreators/NoiseGenerator/NoiseGenerator.cxx
12::/ipldev/scratch/eunyokim/src/BRAINS20111028/BRAINSStandAlone/BRAINSCut/BRAINSFeatureCreators/NoiseGenerator/NoiseGenerator.cxx
32::/ipldev/scratch/eunyokim/src/BRAINS20111028/BRAINSStandAlone/BRAINSCut/BRAINSFeatureCreators/NoiseGenerator/itkAdditiveGaussianNoiseImageFilter.hxx

It fails at the 'New' part. Can any one please help me? The warning message says something has been 'hidden' and I am guessint that part causes the issue. 

Thanks. 

Regina

### CODE REVIEW

**Comment by dmwelch** [comment]
Should this directory exist?  It looks like NoiseGenerator depends on it...

/IPLlinux/ipldev/scratch/eunyokim/src/BRAINS20111028/build-Darwin-Debug/OpenCV-install/share/OpenCV/3rdparty/lib

**Comment by reginakim** [comment]
Really? OpenCV should not be a matter for the Noise Generator. urg. Well. maybe I am wrong. I will look into that as well.  thanks. :) 
On Feb 27, 2012, at 3:59 PM, David Welch wrote:

> /IPLlinux/ipldev/scratch/eunyokim/src/BRAINS20111028/build-Darwin-Debug/OpenCV-install/share/OpenCV/3rdparty/lib

Eun Young(Regina) Kim

Biomedical Engineering Dept.
Univ. of Iowa

Doctorate Student
Psychiatry Iowa
Neuroimaging Consortium
Work Phone : 319-356-4319
Email : eunyoung-kim@uiowa.edu

**Comment by Chaircrusher** [comment]
Make sure that your ThreadedGenerateData has exactly the same function
signature as the parent class
1. in the parent class (itk::ImageSource) it is a virtual function:
   
   virtual
      void ThreadedGenerateData(const OutputImageRegionType &
   outputRegionForThread,
    ThreadIdType threadId);

Is your method virtual?
1. Make sure the argument types match: you are using
   itk::InPlaceImageFilter<TInputImage, TOutputImage>::OutputImageRegionType
   &  and in itk::ImageSource it is itk::ImageSource::OutputImageRegionType.

Are they the same types?  I think problem #1 is more likely

## 

Kent Williams norman-k-williams@uiowa.edu

On 2/27/12 3:47 PM, "eunyoung regina kim"
<reply+i-3409047-f047c5524cca1af43eea7d2f2a53f3a5eaabfc73-482621@reply.gith
ub.com> wrote:

> Hello all,
> 
> Yes I am back, and started to bug you. Sorry and thanks.
> 
> If any of you remember this, I fixed the stupid error I created in the
> xml file. This time, it looks like the 'New' command of the
> 'itkAdditiveGaussianNoiseImageFilter.h' having an issue.
> 
> The code only gives a warning (no error!) as following:
> 
> /ipldev/scratch/eunyokim/src/BRAINS20111028/BRAINSStandAlone/BRAINSCut/BRA
> INSFeatureCreators/NoiseGenerator/itkAdditiveGaussianNoiseImageFilter.h:
> In instantiation of
> Œitk::AdditiveGaussianNoiseImageFilter<itk::Image<float, 3u>,
> itk::Image<float, 3u> >¹:
> /ipldev/scratch/eunyokim/src/BRAINS20111028/BRAINSStandAlone/BRAINSCut/BRA
> INSFeatureCreators/NoiseGenerator/NoiseGenerator.cxx:38:   instantiated
> from here
> /ipldev/scratch/eunyokim/src/BRAINS20111028/build-Darwin-Debug/ITKv4/Modul
> es/Core/Common/include/itkImageSource.hxx:288: warning: Œvoid
> itk::ImageSource<TOutputImage>::ThreadedGenerateData(const typename
> TOutputImage::RegionType&, itk::ThreadIdType) [with TOutputImage =
> itk::Image<float, 3u>]¹ was hidden
> /ipldev/scratch/eunyokim/src/BRAINS20111028/BRAINSStandAlone/BRAINSCut/BRA
> INSFeatureCreators/NoiseGenerator/itkAdditiveGaussianNoiseImageFilter.hxx:
> 42: warning:   by Œvoid
> itk::AdditiveGaussianNoiseImageFilter<TInputImage,
> TOutputImage>::ThreadedGenerateData(const typename
> itk::InPlaceImageFilter<TInputImage,
> TOutputImage>::OutputImageRegionType&, int) [with TInputImage =
> itk::Image<float, 3u>, TOutputImage = itk::Image<float, 3u>]¹
> Linking CXX shared library
> /ipldev/scratch/eunyokim/src/BRAINS20111028/build-Darwin-Debug/lib/libNois
> eGeneratorLib.dylib
> ld: warning: directory not found for option
> '-L/IPLlinux/ipldev/scratch/eunyokim/src/BRAINS20111028/build-Darwin-Debug
> /OpenCV-install/share/OpenCV/3rdparty/lib'
> [ 99%] Built target NoiseGeneratorLib
> Linking CXX executable
> /ipldev/scratch/eunyokim/src/BRAINS20111028/build-Darwin-Debug/lib/NoiseGe
> nerator
> ld: warning: directory not found for option
> '-L/IPLlinux/ipldev/scratch/eunyokim/src/BRAINS20111028/build-Darwin-Debug
> /OpenCV-install/share/OpenCV/3rdparty/lib'
> [100%] Built target NoiseGenerator
> [ 78%] No install step for 'BRAINSTools'
> [ 78%] Completed 'BRAINSTools'
> [100%] Built target BRAINSTools
> 
> And then if I try to run the binary, I get the following error::
> 
> /ipldev/scratch/eunyokim/src/BRAINS20111028/build-Darwin-Debug/lib/NoiseGe
> nerator --inputVolume
> /ipldev/scratch/eunyokim/src/BRAINS20111028/build-Darwin-Debug/ReferenceAt
> las-build/Atlas/Atlas_20120104/template_t1.nii.gz --outputVolume
> ~/Desktop/outputTest.nii.gz --inputGaissianMean 0
> --inputGaussianStandardDeviation 1
> 10::/ipldev/scratch/eunyokim/src/BRAINS20111028/BRAINSStandAlone/BRAINSCut
> /BRAINSFeatureCreators/NoiseGenerator/NoiseGenerator.cxx
> 12::/ipldev/scratch/eunyokim/src/BRAINS20111028/BRAINSStandAlone/BRAINSCut
> /BRAINSFeatureCreators/NoiseGenerator/NoiseGenerator.cxx
> 32::/ipldev/scratch/eunyokim/src/BRAINS20111028/BRAINSStandAlone/BRAINSCut
> /BRAINSFeatureCreators/NoiseGenerator/itkAdditiveGaussianNoiseImageFilter.
> hxx
> 
> It fails at the 'New' part. Can any one please help me? The warning
> message says something has been 'hidden' and I am guessint that part
> causes the issue.
> 
> Thanks.
> 
> Regina
> 
> You can merge this Pull Request by running:
> 
>  git pull https://github.com/reginakim/BRAINSStandAlone master
> 
> Or you can view, comment on it, or merge it online at:
> 
>  https://github.com/BRAINSia/BRAINSStandAlone/pull/46
> 
> -- Commit Summary --
> - DEV: NoiseGenerator Test( DOES NOT WORK)
> - DEV:Make Dump Binary Vector to a Module
> - DEV: Noise Genrator filter generation issue
> 
> -- File Changes --
> 
> M BRAINSCut/BRAINSFeatureCreators/CMakeLists.txt (3)
> A
> BRAINSCut/BRAINSFeatureCreators/DumpBinaryTrainingVectors/CMakeLists.txt
> (10)
> R
> BRAINSCut/BRAINSFeatureCreators/DumpBinaryTrainingVectors/DumpBinaryTraini
> ngVectors.cxx (32)
> A
> BRAINSCut/BRAINSFeatureCreators/DumpBinaryTrainingVectors/DumpBinaryTraini
> ngVectors.xml (45)
> A BRAINSCut/BRAINSFeatureCreators/NoiseGenerator/CMakeLists.txt (10)
> A BRAINSCut/BRAINSFeatureCreators/NoiseGenerator/NoiseGenerator.cxx (58)
> A BRAINSCut/BRAINSFeatureCreators/NoiseGenerator/NoiseGenerator.xml (54)
> A
> BRAINSCut/BRAINSFeatureCreators/NoiseGenerator/itkAdditiveGaussianNoiseIma
> geFilter.h (112)
> A
> BRAINSCut/BRAINSFeatureCreators/NoiseGenerator/itkAdditiveGaussianNoiseIma
> geFilter.hxx (99)
> A
> BRAINSCut/BRAINSFeatureCreators/NoiseGenerator/itkPeakSignalToNoiseRatioCa
> lculator.h (108)
> A
> BRAINSCut/BRAINSFeatureCreators/NoiseGenerator/itkPeakSignalToNoiseRatioCa
> lculator.txx (105)
> A
> BRAINSCut/BRAINSFeatureCreators/NoiseGenerator/itkSaltAndPepperNoiseImageF
> ilter.h (111)
> A
> BRAINSCut/BRAINSFeatureCreators/NoiseGenerator/itkSaltAndPepperNoiseImageF
> ilter.txx (103)
> A
> BRAINSCut/BRAINSFeatureCreators/NoiseGenerator/itkShotNoiseImageFilter.h
> (110)
> A
> BRAINSCut/BRAINSFeatureCreators/NoiseGenerator/itkShotNoiseImageFilter.txx
> (107)
> A
> BRAINSCut/BRAINSFeatureCreators/NoiseGenerator/itkSpeckleNoiseImageFilter.
> h (111)
> A
> BRAINSCut/BRAINSFeatureCreators/NoiseGenerator/itkSpeckleNoiseImageFilter.
> txx (131)
> A BRAINSCut/BRAINSFeatureCreators/NoiseGenerator/itkTestingMacros.h (69)
> A
> BRAINSCut/BRAINSFeatureCreators/NoiseGenerator/itkThreadSafeMersenneTwiste
> rRandomVariateGenerator.h (584)
> 
> -- Patch Links --
> 
>  https://github.com/BRAINSia/BRAINSStandAlone/pull/46.patch
>  https://github.com/BRAINSia/BRAINSStandAlone/pull/46.diff
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/BRAINSia/BRAINSStandAlone/pull/46

---

Notice: This UI Health Care e-mail (including attachments) is covered by the Electronic Communications Privacy Act, 18 U.S.C. 2510-2521, is confidential and may be legally privileged.  If you are not the intended recipient, you are hereby notified that any retention, dissemination, distribution, or copying of this communication is strictly prohibited.  Please reply to the sender that you have received the message in error, then delete it.  Thank you.

---

**Comment by reginakim** [comment]
Thanks, Kent. You are a savor. I will look into that. Technically, that is not MY source code, so I did not have any idea. THANKS SO MUCH!

On Feb 27, 2012, at 4:17 PM, Kent Williams wrote:


Eun Young(Regina) Kim

Biomedical Engineering Dept.
Univ. of Iowa

Doctorate Student
Psychiatry Iowa
Neuroimaging Consortium
Work Phone : 319-356-4319
Email : eunyoung-kim@uiowa.edu

**Comment by hjmjohnson** [comment]
Regina,

I am closing this pull request under the assumption that more work needs to be done to this patch set.  Please push another pull request when the issues are resolved to your satisfaction.

Hans

**Pull request closed without merging**
