### PR TITLE
ENH: Added test for gtractResampleDWIInPlace

### PR DESCRIPTION
**Pull request by dmwelch**
Test builds and runs (currently fails)

### CODE REVIEW

**Comment by dmwelch** [comment]
Renamed GTRACT testing directory to BRAINSTools 'TestSuite' for consistancy.  
Commented out other legacy GTRACT tests until I can fix them.

**Comment by dmwelch** [comment]
Removed commented lines and replaced with if( FALSE ) clause

**Comment by dmwelch** [comment]
All GTRACT tests build now.

**Comment by hjmjohnson** [comment]
@dmwelch based on our discussion, I'm just going to leave this patch set linger until you have an opportunity to get back to it.  I think it is better at this point to wait until the test can be made to pass rather than push through the the change that will force failing cases.

**Pull request closed without merging**
